=== ThULB/jportal/jportal_mcr_module/src/main/resources/datamodel-jpinst.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd" />
  <xsd:import namespace="http://www.w3.org/1999/xlink" schemaLocation="http://www.w3.org/XML/2008/06/xlink.xsd" />
  <xsd:simpleType name="mcrdefaulttype">
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="256" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="mcrdefaultform">
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="256" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="mcrdateformat">
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="256" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="mcrobjectid">
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="64" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="mcrcategory">
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="128" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="mcrdimension">
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="128" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="mcrmeasurement">
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="64" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:element name="mycoreobject" type="MCRObject" />
  <xsd:complexType name="MCRObject">
    <xsd:all>
      <xsd:element name="structure" type="MCRObjectStructure" minOccurs="1" maxOccurs="1" />
      <xsd:element name="metadata" type="MCRObjectMetadata" minOccurs="1" maxOccurs="1" />
      <xsd:element name="service" type="MCRObjectService" minOccurs="1" maxOccurs="1" />
    </xsd:all>
    <xsd:attribute name="ID" type="xsd:string" use="required" />
    <xsd:attribute name="label" type="xsd:string" use="required" />
    <xsd:attribute name="version" type="xsd:string" use="optional" />
  </xsd:complexType>
  <xsd:complexType name="MCRObjectStructure">
    <xsd:sequence>
      <xsd:element name="derobjects" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="derobject" minOccurs="0" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                <xsd:attribute ref="xlink:type" />
                <xsd:attribute ref="xlink:href" use="optional" />
                <xsd:attribute ref="xlink:title" use="optional" />
                <xsd:attribute ref="xlink:label" use="optional" />
                <xsd:attribute ref="xlink:role" use="optional" />
                <xsd:attribute ref="xlink:from" use="optional" />
                <xsd:attribute ref="xlink:to" use="optional" />
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaLinkID" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute ref="xml:lang" />
  </xsd:complexType>
  <xsd:complexType name="MCRObjectMetadata">
    <xsd:all>
      <xsd:element name="names" minOccurs="1" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:all>
                  <xsd:element name="fullname" type="xsd:string" minOccurs="1" maxOccurs="1" />
                  <xsd:element name="nickname" type="xsd:string" minOccurs="0" maxOccurs="1" />
                  <xsd:element name="property" type="xsd:string" minOccurs="0" maxOccurs="1" />
                </xsd:all>
                <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                <xsd:attribute ref="xml:lang" />
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaInstitutionName" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="alternatives" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="alternative" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType mixed="true">
                <xsd:sequence maxOccurs="unbounded">
                  <xsd:any namespace="##any" minOccurs="0" processContents="skip" />
                </xsd:sequence>
                <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                <xsd:attribute ref="xml:lang" use="optional" />
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaXML" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="addresses" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="address" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:all>
                  <xsd:element name="country" type="xsd:string" minOccurs="0" maxOccurs="1" />
                  <xsd:element name="state" type="xsd:string" minOccurs="0" maxOccurs="1" />
                  <xsd:element name="zipcode" type="xsd:string" minOccurs="0" maxOccurs="1" />
                  <xsd:element name="city" type="xsd:string" minOccurs="0" maxOccurs="1" />
                  <xsd:element name="street" type="xsd:string" minOccurs="0" maxOccurs="1" />
                  <xsd:element name="number" type="xsd:string" minOccurs="0" maxOccurs="1" />
                </xsd:all>
                <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                <xsd:attribute ref="xml:lang" />
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaAddress" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="phones" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="phone" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:simpleContent>
                  <xsd:extension base="xsd:string">
                    <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                    <xsd:attribute name="form" use="optional" type="mcrdefaultform" />
                    <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                    <xsd:attribute ref="xml:lang" />
                  </xsd:extension>
                </xsd:simpleContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaLangText" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="urls" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="url" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                <xsd:attribute ref="xlink:type" />
                <xsd:attribute ref="xlink:href" use="optional" />
                <xsd:attribute ref="xlink:title" use="optional" />
                <xsd:attribute ref="xlink:label" use="optional" />
                <xsd:attribute ref="xlink:role" use="optional" />
                <xsd:attribute ref="xlink:from" use="optional" />
                <xsd:attribute ref="xlink:to" use="optional" />
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaLink" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="emails" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="email" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:simpleContent>
                  <xsd:extension base="xsd:string">
                    <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                    <xsd:attribute name="form" use="optional" type="mcrdefaultform" />
                    <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                    <xsd:attribute ref="xml:lang" />
                  </xsd:extension>
                </xsd:simpleContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaLangText" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="notes" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="note" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:simpleContent>
                  <xsd:extension base="xsd:string">
                    <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                    <xsd:attribute name="form" use="optional" type="mcrdefaultform" />
                    <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                    <xsd:attribute ref="xml:lang" />
                  </xsd:extension>
                </xsd:simpleContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaLangText" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="identifiers" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="identifier" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:simpleContent>
                  <xsd:extension base="xsd:string">
                    <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                    <xsd:attribute name="form" use="optional" type="mcrdefaultform" />
                    <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                    <xsd:attribute ref="xml:lang" />
                  </xsd:extension>
                </xsd:simpleContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaLangText" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="def.doubletOf" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="doubletOf" minOccurs="1" maxOccurs="1">
              <xsd:complexType>
                <xsd:simpleContent>
                  <xsd:extension base="xsd:string">
                    <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                    <xsd:attribute name="form" use="optional" type="mcrdefaultform" />
                    <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                    <xsd:attribute ref="xml:lang" />
                  </xsd:extension>
                </xsd:simpleContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaLangText" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
    </xsd:all>
    <xsd:attribute ref="xml:lang" use="optional" />
  </xsd:complexType>
  <xsd:complexType name="MCRObjectService">
    <xsd:all>
      <xsd:element name="servdates" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="servdate" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:simpleContent>
                  <xsd:extension base="xsd:string">
                    <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                    <xsd:attribute name="format" use="optional" type="mcrdateformat" />
                    <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                  </xsd:extension>
                </xsd:simpleContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaISO8601Date" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="servflags" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="servflag" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:simpleContent>
                  <xsd:extension base="xsd:string">
                    <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                    <xsd:attribute name="form" use="optional" type="mcrdefaultform" />
                    <xsd:attribute name="inherited" use="optional" type="xsd:integer" />
                    <xsd:attribute ref="xml:lang" />
                  </xsd:extension>
                </xsd:simpleContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaLangText" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="servacls" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="servacl" minOccurs="1" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:any processContents="skip" />
                </xsd:sequence>
                <xsd:attribute name="permission" use="required" type="xsd:string" />
                <xsd:attribute name="inherited" use="optional" type="xsd:string" />
                <xsd:attribute name="type" use="optional" type="mcrdefaulttype" />
                <xsd:attribute ref="xml:lang" use="optional" />
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="class" type="xsd:string" use="required" fixed="MCRMetaAccessRule" />
          <xsd:attribute name="heritable" type="xsd:boolean" use="optional" />
          <xsd:attribute name="notinherit" type="xsd:boolean" use="optional" />
        </xsd:complexType>
      </xsd:element>
    </xsd:all>
    <xsd:attribute ref="xml:lang" />
  </xsd:complexType>
</xsd:schema>

=== ThULB/jportal/jportal_sample_data/src/main/resources/jportal_jpinst_00000001.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreobject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" ID="jportal_jpinst_00000001"
  label="jportal_jpinst_00000001" version="2.0" xsi:noNamespaceSchemaLocation="datamodel-jpinst.xsd">
  <structure />
  <metadata xml:lang="de">
    <names class="MCRMetaInstitutionName" heritable="true" notinherit="false">
      <name inherited="0">
        <fullname>Spiegel-Verlag</fullname>
        <property>GmbH &amp; Co. KG</property>
      </name>
    </names>
    <addresses class="MCRMetaAddress" heritable="true" notinherit="false">
      <address inherited="0">
        <country>Deutschland</country>
        <zipcode>20457</zipcode>
        <city>Hamburg</city>
        <street>Ericusspitze</street>
        <number>1</number>
      </address>
    </addresses>
    <phones class="MCRMetaLangText" heritable="true" notinherit="false">
      <phone xml:lang="de" type="Telefon" inherited="0" form="plain">040
        3007-0
      </phone>
      <phone xml:lang="de" type="Fax" inherited="0" form="plain">040
        3007-2246
      </phone>
    </phones>
    <urls class="MCRMetaLink" heritable="true" notinherit="false">
      <url inherited="0" xlink:type="locator" xlink:title="spiegel-gruppe" xlink:href="http://www.spiegelgruppe.de" />
    </urls>
    <emails class="MCRMetaLangText" heritable="true" notinherit="false">
      <email inherited="0" form="plain">spiegel@spiegel.de</email>
    </emails>
  </metadata>
  <service>
    <servdates class="MCRMetaISO8601Date">
      <servdate type="modifydate" inherited="0">2014-04-03T14:26:27.380Z</servdate>
      <servdate type="createdate" inherited="0">2014-04-03T14:26:27.380Z</servdate>
    </servdates>
    <servflags class="MCRMetaLangText">
      <servflag type="createdby" inherited="0" form="plain">administrator</servflag>
      <servflag type="modifiedby" inherited="0" form="plain">administrator</servflag>
    </servflags>
  </service>
</mycoreobject>

=== ThULB/jportal/jportal_mcr_module/src/test/resources/logoRescourceTest/inst30.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreobject xmlns:acl="xalan://org.mycore.access.MCRAccessManager" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink" ID="jportal_jpinst_00000030" label="jportal_jpinst_00000030" version="2.0"
    xsi:noNamespaceSchemaLocation="datamodel-jpinst.xsd">
    <structure />
    <metadata>
        <names class="MCRMetaInstitutionName" heritable="true" notinherit="false">
            <name inherited="0">
                <fullname>Willkommen in der ThULB</fullname>
            </name>
        </names>
        <logo class="MCRMetaLangText" heritable="true" notinherit="false">
            <url type="logoPlain" inherited="0" form="plain">http://localhost:8291/logos/test.svg</url>

            <url type="logoPlusText" inherited="0" form="plain">http://localhost:8291/logos/testPlusText.svg</url>
        </logo>
    </metadata>
    <service>
        <servdates class="MCRMetaISO8601Date">
            <servdate type="modifydate" inherited="0">2012-01-26T17:13:49.404Z</servdate>
            <servdate type="createdate" inherited="0">2012-01-26T17:13:49.404Z</servdate>
        </servdates>

    </service>
</mycoreobject>
