=== ThULB/jportal/mycore/schema/editor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp1 U (http://www.xmlspy.com) by Lützenkirchen, Frank (Universität Duisburg-Essen) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml-2001.xsd"/>
	<xs:element name="editor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="include" minOccurs="0"/>
				<xs:element name="source" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="url" type="xs:anyURI" use="required"/>
						<xs:attribute name="token" type="xs:string" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="target">
					<xs:complexType>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="servlet"/>
									<xs:enumeration value="debug"/>
									<xs:enumeration value="display"/>
									<xs:enumeration value="url"/>
									<xs:enumeration value="subselect"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="name" type="xs:string" use="optional"/>
						<xs:attribute name="url" type="xs:anyURI" use="optional"/>
						<xs:attribute name="method" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="get"/>
									<xs:enumeration value="post"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="format" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="xml"/>
									<xs:enumeration value="name=value"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="validationMessage" type="labelOutputType" minOccurs="0"/>
				<xs:element ref="include" minOccurs="0"/>
				<xs:element name="components">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="headline" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:choice maxOccurs="unbounded">
											<xs:element ref="text"/>
											<xs:element ref="output"/>
										</xs:choice>
									</xs:sequence>
									<xs:attribute ref="anchor" use="optional"/>
								</xs:complexType>
							</xs:element>
							<xs:choice maxOccurs="unbounded">
								<xs:element ref="panel"/>
								<xs:element ref="repeater"/>
								<xs:element ref="text"/>
								<xs:element ref="output"/>
								<xs:element ref="display"/>
								<xs:element ref="textfield"/>
								<xs:element ref="textarea"/>
								<xs:element ref="password"/>
								<xs:element ref="file"/>
								<xs:element ref="list"/>
								<xs:element ref="checkbox"/>
								<xs:element ref="space"/>
								<xs:element ref="button"/>
								<xs:element ref="submitButton"/>
								<xs:element ref="cancelButton"/>
								<xs:element ref="helpPopup"/>
								<xs:element ref="subselect"/>
								<xs:element ref="include"/>
							</xs:choice>
						</xs:sequence>
						<xs:attribute ref="var" use="optional"/>
						<xs:attribute name="root" type="xs:IDREF" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element ref="include" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
			<xs:attribute name="validate" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="panel">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="cell" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice minOccurs="0">
							<xs:element ref="panel"/>
							<xs:element ref="repeater"/>
							<xs:element ref="text"/>
							<xs:element ref="output"/>
							<xs:element ref="display"/>
							<xs:element ref="textfield"/>
							<xs:element ref="textarea"/>
							<xs:element ref="password"/>
							<xs:element ref="file"/>
							<xs:element ref="list"/>
							<xs:element ref="checkbox"/>
							<xs:element ref="space"/>
							<xs:element ref="button"/>
							<xs:element ref="submitButton"/>
							<xs:element ref="cancelButton"/>
							<xs:element ref="helpPopup"/>
							<xs:element ref="subselect"/>
							<xs:element ref="include"/>
						</xs:choice>
						<xs:attribute name="row" use="optional" default="1">
							<xs:simpleType>
								<xs:restriction base="xs:int">
									<xs:minInclusive value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="col" use="optional" default="1">
							<xs:simpleType>
								<xs:restriction base="xs:int">
									<xs:minInclusive value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="colspan" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:int">
									<xs:minInclusive value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute ref="sortnr" use="optional"/>
						<xs:attribute ref="var" use="optional"/>
						<xs:attribute ref="anchor" use="optional"/>
						<xs:attribute name="height" type="xs:string" use="optional"/>
						<xs:attribute name="width" type="xs:string" use="optional"/>
						<xs:attribute name="ref" type="xs:IDREF" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="hidden" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute ref="var" use="required"/>
						<xs:attribute name="default" type="xs:string" use="optional"/>
						<xs:attribute name="descendants" type="xs:boolean" use="optional"/>
						<xs:attribute ref="sortnr" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element ref="condition" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="include" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute ref="lines" use="optional" default="off"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="condition">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="labelOutputType">
					<xs:attribute name="id" type="xs:ID" use="required"/>
					<xs:attribute name="field1" type="varPath" use="optional"/>
					<xs:attribute name="field2" type="varPath" use="optional"/>
					<xs:attribute name="type" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="string"/>
								<xs:enumeration value="integer"/>
								<xs:enumeration value="decimal"/>
								<xs:enumeration value="datetime"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="operator" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="="/>
								<xs:enumeration value="&gt;"/>
								<xs:enumeration value="&lt;"/>
								<xs:enumeration value="&gt;="/>
								<xs:enumeration value="&lt;="/>
								<xs:enumeration value="!="/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="format" type="xs:string" use="optional"/>
					<xs:attribute name="class" type="xs:string" use="optional"/>
					<xs:attribute name="method" type="xs:string" use="optional"/>
					<xs:attribute name="xsl" type="xs:string" use="optional"/>
					<xs:attribute name="min" type="xs:string" use="optional"/>
					<xs:attribute name="max" type="xs:string" use="optional"/>
					<xs:attribute name="minLength" type="xs:int" use="optional"/>
					<xs:attribute name="maxLength" type="xs:int" use="optional"/>
					<xs:attribute name="regexp" type="xs:string" use="optional"/>
					<xs:attribute name="required" type="xs:boolean" use="optional" default="false"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="text">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="labelOutputType">
					<xs:attribute name="id" type="xs:ID" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="output">
		<xs:complexType>
			<xs:attribute name="default" type="xs:string" use="optional"/>
			<xs:attribute ref="var" use="optional"/>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="display">
		<xs:complexType>
			<xs:attribute name="default" type="xs:string" use="optional"/>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="textfield" type="textInputType"/>
	<xs:element name="textarea">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="textInputType">
					<xs:attribute name="height" type="xs:int" use="required"/>
					<xs:attribute name="wrap" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="off"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="wysiwygEditor" type="xs:boolean" use="optional" default="false"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="password">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="condition" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="width" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="file">
		<xs:complexType>
			<xs:attribute name="width" type="xs:int" use="required"/>
			<xs:attribute name="accept" type="xs:string" use="optional"/>
			<xs:attribute name="maxlength" type="xs:string" use="optional"/>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="checkbox">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="labelOutputType">
					<xs:sequence minOccurs="0">
						<xs:element ref="condition" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="value" type="xs:string" use="required"/>
					<xs:attribute name="checked" type="xs:boolean" use="optional" default="false"/>
					<xs:attribute name="id" type="xs:ID" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="item" maxOccurs="unbounded"/>
					<xs:element ref="condition" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="include" minOccurs="0" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="dropdown"/>
						<xs:enumeration value="checkbox"/>
						<xs:enumeration value="radio"/>
						<xs:enumeration value="multirow"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="default" type="xs:string" use="optional"/>
			<xs:attribute name="multiple" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="rows" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="cols" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="width" type="xs:string" use="optional"/>
			<xs:attribute name="disabled" type="xs:boolean" use="optional" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="labelOutputType">
					<xs:sequence minOccurs="0">
						<xs:choice>
							<xs:element ref="item" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element ref="include" minOccurs="0" maxOccurs="unbounded"/>
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="value" type="xs:string" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="space">
		<xs:complexType>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="width" type="xs:string" use="optional"/>
			<xs:attribute name="height" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="button">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="buttonType">
					<xs:attribute name="url" type="xs:anyURI" use="required"/>
					<xs:attribute name="id" type="xs:ID" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="submitButton">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="buttonType">
					<xs:attribute name="id" type="xs:ID" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="cancelButton">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="buttonType">
					<xs:attribute name="id" type="xs:ID" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="repeater">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="panel"/>
				<xs:element ref="output"/>
				<xs:element ref="display"/>
				<xs:element ref="textfield"/>
				<xs:element ref="textarea"/>
				<xs:element ref="password"/>
				<xs:element ref="file"/>
				<xs:element ref="list"/>
				<xs:element ref="checkbox"/>
				<xs:element ref="subselect"/>
				<xs:element ref="include"/>
			</xs:choice>
			<xs:attribute name="min" type="xs:int" use="required"/>
			<xs:attribute name="max" type="xs:int" use="required"/>
			<xs:attribute ref="lines" use="optional" default="off"/>
			<xs:attribute name="pos" use="optional" default="right">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="left"/>
						<xs:enumeration value="right"/>
						<xs:enumeration value="hidden"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="include">
		<xs:complexType>
			<xs:attribute name="uri" type="xs:string" use="optional"/>
			<xs:attribute name="ref" type="xs:IDREF" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="helpPopup">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="labelOutputType">
					<xs:sequence>
						<xs:choice>
							<xs:element name="button" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute ref="xml:lang" use="optional"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="title" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute ref="xml:lang" use="optional"/>
								</xs:complexType>
							</xs:element>
							<xs:element ref="include"/>
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="xs:ID" use="required"/>
					<xs:attribute name="width" type="xs:int" use="required"/>
					<xs:attribute name="height" type="xs:int" use="required"/>
					<xs:attribute name="css" type="xs:string" use="optional"/>
					<xs:attribute name="title" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="subselect">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="buttonType">
					<xs:attribute name="id" type="xs:ID" use="required"/>
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="editor"/>
								<xs:enumeration value="servlet"/>
								<xs:enumeration value="webpage"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="href" type="xs:anyURI" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:attribute name="sortnr" type="xs:int" id="sortnr"/>
	<xs:attribute name="var" type="varPath" id="var"/>
	<xs:attribute name="anchor" default="WEST" id="anchor">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="NORTH"/>
				<xs:enumeration value="NORTHEAST"/>
				<xs:enumeration value="EAST"/>
				<xs:enumeration value="SOUTHEAST"/>
				<xs:enumeration value="SOUTH"/>
				<xs:enumeration value="SOUTHWEST"/>
				<xs:enumeration value="WEST"/>
				<xs:enumeration value="NORTHWEST"/>
				<xs:enumeration value="CENTER"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="lines" id="lines">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="on"/>
				<xs:enumeration value="off"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:simpleType name="varPath">
		<xs:restriction base="xs:string">
			<xs:pattern value="/?@?[a-zA-Z0-9\-_\.]+(\[@[a-zA-Z0-9\-_\.]+=&apos;[a-zA-Z0-9\-_\.]+&apos;\])?(\[[1-9]+[0-9]*\])?(/@?[a-zA-Z0-9\-_\.]+(\[@[a-zA-Z0-9\-_\.]+=&apos;[a-zA-Z0-9\-_\.]+&apos;\])?(\[[1-9]+[0-9]*\])?)*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="labelOutputType">
		<xs:sequence minOccurs="0">
			<xs:element name="label" maxOccurs="unbounded">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:any namespace="http://www.w3.org/1999/xhtml" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="i18n" type="xs:string" use="optional"/>
					<xs:attribute name="css-style" type="xs:string" use="optional"/>
					<xs:attribute ref="xml:lang" use="optional"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="i18n" type="xs:string" use="optional"/>
		<xs:attribute name="label" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="textInputType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="default" type="xs:string" minOccurs="0"/>
				<xs:element name="autofill" type="xs:string" minOccurs="0"/>
			</xs:choice>
			<xs:element ref="condition" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="default" type="xs:string" use="optional"/>
		<xs:attribute name="autofill" type="xs:string" use="optional"/>
		<xs:attribute name="id" type="xs:ID" use="optional"/>
		<xs:attribute name="width" type="xs:int" use="required"/>
		<xs:attribute name="maxlength" type="xs:int" use="optional"/>
	</xs:complexType>
	<xs:complexType name="anyComponent">
		<xs:choice>
			<xs:element ref="panel"/>
			<xs:element ref="text"/>
			<xs:element ref="output"/>
			<xs:element ref="display"/>
			<xs:element ref="textfield"/>
			<xs:element ref="textarea"/>
			<xs:element ref="password"/>
			<xs:element ref="file"/>
			<xs:element ref="list"/>
			<xs:element ref="checkbox"/>
			<xs:element ref="space"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="buttonType">
		<xs:complexContent>
			<xs:extension base="labelOutputType">
				<xs:attribute name="width" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== ThULB/jportal/application/modules/module-jportal/config/imports-person.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<components xmlns:xhtml="http://www.w3.org/1999/xhtml"
	xsi:noNamespaceSchemaLocation="editor.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<include uri="webapp:editor/editor-commons.xml"/>
	
	<panel id="globalImport.person" lines="on">
		<hidden var="@ID"/>
		<hidden var="@label"/>
		<cell col="1" row="1" var="metadata">
			<panel>
				<cell col="1" row="1" anchor="NORTHWEST" ref="Lheading"/>
				<cell col="2" row="1" anchor="NORTHWEST" ref="Dheading"
					var="def.heading"/>
				<cell col="3" row="1" anchor="WEST" ref="Hheading"/>
				
				<cell col="1" row="2" anchor="NORTHWEST" ref="Lalternative"/>
				<cell col="2" row="2" anchor="NORTHWEST" ref="Dalternative"
					var="def.alternative"/>
				<cell col="3" row="2" anchor="WEST" ref="Halternative"/>
				
				<cell col="1" row="3" anchor="NORTHWEST" ref="Lpeerage"/>
				<cell col="2" row="3" anchor="NORTHWEST" ref="Dpeerage"
					var="def.peerage"/>
				<cell col="3" row="3" anchor="WEST" ref="Hpeerage"/>
				
				<cell col="1" row="4" anchor="NORTHWEST" ref="Lgender"/>
				<cell col="2" row="4" anchor="NORTHWEST" ref="Dgender"
					var="def.gender"/>
				<cell col="3" row="4" anchor="WEST" ref="Hgender"/>
				
				<cell col="1" row="5" anchor="NORTHWEST" ref="Lrole"/>
				<cell col="2" row="5" anchor="NORTHWEST" ref="Drole" var="def.role"/>
				<cell col="3" row="5" anchor="WEST" ref="Hrole"/>
				
				<cell col="1" row="6" anchor="NORTHWEST" ref="LplaceOfActivity"/>
				<cell col="2" row="6" anchor="NORTHWEST" ref="DplaceOfActivity"
					var="def.placeOfActivity"/>
				<cell col="3" row="6" anchor="WEST" ref="HplaceOfActivity"/>
				
				<cell col="1" row="7" anchor="NORTHWEST" ref="LdateOfBirth"/>
				<cell col="2" row="7" anchor="NORTHWEST" ref="DdateOfBirth"
					var="def.dateOfBirth"/>
				<cell col="3" row="7" anchor="WEST" ref="HdateOfBirth"/>
				
				<cell col="1" row="8" anchor="NORTHWEST" ref="LplaceOfBirth"/>
				<cell col="2" row="8" anchor="NORTHWEST" ref="DplaceOfBirth"
					var="def.placeOfBirth"/>
				<cell col="3" row="8" anchor="WEST" ref="HplaceOfBirth"/>
				
				<cell col="1" row="9" anchor="NORTHWEST" ref="LdateOfDeath"/>
				<cell col="2" row="9" anchor="NORTHWEST" ref="DdateOfDeath"
					var="def.dateOfDeath"/>
				<cell col="3" row="9" anchor="WEST" ref="HdateOfDeath"/>
				
				<cell col="1" row="10" anchor="NORTHWEST" ref="LplaceOfDeath"/>
				<cell col="2" row="10" anchor="NORTHWEST" ref="DplaceOfDeath"
					var="def.placeOfDeath"/>
				<cell col="3" row="10" anchor="WEST" ref="HplaceOfDeath"/>
				
				<cell col="1" row="11" anchor="NORTHWEST" ref="Lnote"/>
				<cell col="2" row="11" anchor="NORTHWEST" ref="Dnote"
					var="def.note"/>
				<cell col="3" row="11" anchor="WEST" ref="Hnote"/>
				
				<cell col="1" colspan="2" row="12" anchor="EAST" ref="TwoButtons"/>
				<cell col="2" row="12"/>
			</panel>
		</cell>
	</panel>
	
	<panel id="personName">
		<cell col="1" row="1" anchor="NORTHWEST" var="lastName">
			<label xml:lang="de">
				<xhtml:span class="editorlabel">Nachname: </xhtml:span>
			</label>
		</cell>		
		<cell col="2" row="1" anchor="NORTHWEST" var="lastName">
			<textfield width="16" maxlength="128"/>
		</cell>
		
		<cell col="1" row="2" anchor="NORTHWEST" var="lastName">
			<label xml:lang="de">
				<xhtml:span class="editorlabel">Vorname: </xhtml:span>
			</label>
		</cell>				
		<cell col="2" row="2" anchor="NORTHWEST" var="firstName">
			<textfield width="16" maxlength="128"/>
		</cell>
	</panel>
	
	<!-- *** Ansetzungsform: Name ** -->
	<panel id="Dheading">
		<hidden var="@class" default="MCRMetaXML"/>
		<hidden var="@notinherit" default="true"/>
		<hidden var="@heritable" default="true"/>
		<cell col="1" row="1" anchor="NORTHWEST" var="heading" ref="personName"/>
	</panel>
	<text id="Lheading">
		<label xml:lang="de">
			<xhtml:span class="editorlabel">&#160;Name in Ansetzungsform (*)
				&#160;</xhtml:span>
		</label>
	</text>
	<helpPopup id="Hheading" width="400" height="250">
		<label xml:lang="de">Name in Ansetzungsform</label>
	</helpPopup>
	
	<!-- *** Namensformen ** -->
	<panel id="Dalternative">
		<hidden var="@class" default="MCRMetaXML"/>
		<hidden var="@notinherit" default="true"/>
		<hidden var="@heritable" default="true"/>
		<cell col="1" row="1" anchor="NORTHWEST"
			var="alternative[@type='complete']">
			<repeater min="0" max="10" ref="personName"/>
		</cell>
		<cell col="1" row="2" anchor="NORTHWEST" var="alternative[@type='single']">
			<repeater min="0" max="10">
				<panel>
					<cell var="name">
						<textfield width="35" maxlength="128"/>
					</cell>
				</panel>
			</repeater>
		</cell>
	</panel>
	<text id="Lalternative">
		<label xml:lang="de">
			<xhtml:span class="editorlabel">&#160;Weitere Namensformen
				&#160;</xhtml:span>
		</label>
	</text>
	<helpPopup id="Halternative" width="400" height="250">
		<label xml:lang="de">Hier können alternative zum leichteren Auffinden des
			Objektes eingetragen werden.</label>
	</helpPopup>
	
	<!-- *** Geschlecht ** -->
	<panel id="Dgender">
		<hidden var="@class" default="MCRMetaClassification"/>
		<hidden var="@notinherit" default="true"/>
		<hidden var="@heritable" default="true"/>
		<cell col="1" row="1" anchor="NORTHWEST" var="gender">
			<panel>
				<hidden var="@classid" default="urmel_class_00000001"/>
				<hidden var="@inherited" default="0"/>
				<cell var="@categid"  >
					<list width="300" type="radio" default="unknown">
						<include
							uri="classification:editor:-1:children:urmel_class_00000001"/>
					</list>
				</cell>
			</panel>
		</cell>
	</panel>
	<text id="Lgender">
		<label xml:lang="de">
			<xhtml:span class="editorlabel">&#160;Geschlecht (*)
				&#160;</xhtml:span>
		</label>
	</text>
	<helpPopup id="Hgender" width="400" height="250">
		<label xml:lang="de">Wählen sie das Geschlecht aus</label>
	</helpPopup>
	
	<!-- *** Adelstitel ** -->
	<panel id="Dpeerage">
		<hidden var="@class" default="MCRMetaLangText"/>
		<hidden var="@notinherit" default="true"/>
		<hidden var="@heritable" default="true"/>
		<cell col="1" row="1" anchor="NORTHWEST" var="peerage" ref="TFzeile128"/>
	</panel>
	<text id="Lpeerage">
		<label xml:lang="de">
			<xhtml:span class="editorlabel">&#160;Adelstitel
				&#160;</xhtml:span>
		</label>
	</text>
	<helpPopup id="Hpeerage" width="400" height="250">
		<label xml:lang="de">Adelstitel, z.B. Graf</label>
	</helpPopup>
	
	<!-- *** Ämter und Funktionen ** -->
	<panel id="Drole">
		<hidden var="@class" default="MCRMetaLangText"/>
		<hidden var="@notinherit" default="true"/>
		<hidden var="@heritable" default="true"/>
		<cell col="1" row="1" anchor="NORTHWEST" var="role">
			<repeater min="0" max="10" ref="repeater32"/>
		</cell>
	</panel>
	<text id="Lrole">
		<label xml:lang="de">
			<xhtml:span class="editorlabel">&#160;Ämter und Funktionen
				&#160;</xhtml:span>
		</label>
	</text>
	<helpPopup id="Hrole" width="400" height="250">
		<label xml:lang="de"> Hier können Ämter und Funktionen eingetragen werden, z.B.
			"Professor für Geschichte". </label>
	</helpPopup>
	
	<!-- *** Lebens- und Wirkungsorte ** -->
	<panel id="DplaceOfActivity">
		<hidden var="@class" default="MCRMetaLangText"/>
		<hidden var="@notinherit" default="true"/>
		<hidden var="@heritable" default="true"/>
		<cell col="1" row="1" anchor="NORTHWEST" var="placeOfActivity">
			<repeater min="0" max="10" ref="repeater32"/>
		</cell>
	</panel>
	<text id="LplaceOfActivity">
		<label xml:lang="de">
			<xhtml:span class="editorlabel">&#160;Lebens- und Wirkungsorte
				&#160;</xhtml:span>
		</label>
	</text>
	<helpPopup id="HplaceOfActivity" width="400" height="250">
		<label xml:lang="de"> Hier können Lebens- und Wirkungsorte eingetragen werden,
			z.B. "Jena". </label>
	</helpPopup>
	
	<!-- *** Geburtsdatum ** -->
	<panel id="DdateOfBirth">
		<hidden var="@class" default="MCRMetaISO8601Date"/>
		<hidden var="@notinherit" default="true"/>
		<hidden var="@heritable" default="true"/>
		<cell col="1" row="1" anchor="NORTHWEST" var="dateOfBirth" ref="TFzeile10"/>
	</panel>
	<text id="LdateOfBirth">
		<label xml:lang="de">
			<xhtml:span class="editorlabel">&#160;Geburtsdatum
				&#160;</xhtml:span>
		</label>
	</text>
	<helpPopup id="HdateOfBirth" width="400" height="250">
		<label xml:lang="de"> Geben sie bitte das Geburtsdatum - so weit bekannt - ein.
			Dieses muss in der Form JJJJ-MM-TT eingegeben werden. Falls nicht näher
			bekannt, können Monat und Tag weggelassen werden. </label>
	</helpPopup>
	
	<!-- *** Geburtsort ** -->
	<panel id="DplaceOfBirth">
		<hidden var="@class" default="MCRMetaLangText"/>
		<hidden var="@notinherit" default="true"/>
		<hidden var="@heritable" default="true"/>
		<cell col="1" row="1" anchor="NORTHWEST" var="placeOfBirth"
			ref="TFzeile128"/>
	</panel>
	<text id="LplaceOfBirth">
		<label xml:lang="de">
			<xhtml:span class="editorlabel">&#160;Geburtsort
				&#160;</xhtml:span>
		</label>
	</text>
	<helpPopup id="HplaceOfBirth" width="400" height="250">
		<label xml:lang="de">Sie können hier den Geburtsort der Person angeben.</label>
	</helpPopup>
	
	<!-- *** Sterbedatum ** -->
	<panel id="DdateOfDeath">
		<hidden var="@class" default="MCRMetaISO8601Date"/>
		<hidden var="@notinherit" default="true"/>
		<hidden var="@heritable" default="true"/>
		<cell col="1" row="1" anchor="NORTHWEST" var="dateOfDeath" ref="TFzeile10"/>
	</panel>
	<text id="LdateOfDeath">
		<label xml:lang="de">
			<xhtml:span class="editorlabel">&#160;Sterbedatum
				&#160;</xhtml:span>
		</label>
	</text>
	<helpPopup id="HdateOfDeath" width="400" height="250">
		<label xml:lang="de"> Geben sie bitte das Sterbedatum - so weit bekannt - ein. Dieses
			muss in der Form JJJJ-MM-TT eingegeben werden. Falls nicht näher bekannt,
			können Monat und Tag weggelassen werden. </label>
	</helpPopup>
	
	<!-- *** Sterbeort ** -->
	<panel id="DplaceOfDeath">
		<cell col="1" row="1" anchor="NORTHWEST" var="placeOfDeath"
			ref="TFzeile128"/>
