=== ThULB/jportal/mycore/schema/fieldtypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mcr="http://www.mycore.org/" targetNamespace="http://www.mycore.org/" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="fieldtypes">
		<xs:annotation>
			<xs:documentation>defines supported datatypes and search operatores of search fields</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="type" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="operator" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="token" type="mcr:operator" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:NCName" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="operator">
		<xs:annotation>
			<xs:documentation>operators may consist of any character except whitespace</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="\S*"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ThULB/jportal/jpApp/modules/jportal/tests/resources/fieldtypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<fieldtypes xmlns="http://www.mycore.org/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mycore.org/
fieldtypes.xsd">

	<type name="identifier" default="=">
		<!-- exact string or id, should be indexed unchanged -->
		<operator token="="/>
		<operator token="&gt;"/>
		<operator token="&lt;"/>
		<operator token="&gt;="/>
		<operator token="&lt;="/>
		<operator token="like"/>
		<!-- allows wildcard search using * and ? -->
	</type>
	<type name="name" default="contains">
		<!-- name of a person or place, umlauts etc. should be normalized -->
		<operator token="="/>
		<operator token="&gt;"/>
		<operator token="&lt;"/>
		<operator token="&gt;="/>
		<operator token="&lt;="/>
		<operator token="like"/>
		<!-- allows wildcard search using * and ? -->
		<operator token="contains"/>
		<!-- searches words at any position in the text -->
	</type>
	<type name="text" default="contains">
		<!-- free text like title, abstract ect., stemming and linguistic processing applied -->
		<operator token="="/>
		<operator token="&gt;"/>
		<operator token="&lt;"/>
		<operator token="&gt;="/>
		<operator token="&lt;="/>
		<operator token="like"/>
		<!-- allows wildcard search using * and ? -->
		<operator token="contains"/>
		<!-- searches words at any position in the text -->
		<operator token="phrase"/>
		<!-- searches a phrase at any position in the text -->
	</type>
	<type name="date" default="=">
		<!-- date value in ISO-8601 format "yyyy-MM-dd" -->
		<operator token="="/>
		<operator token="&gt;"/>
		<operator token="&lt;"/>
		<operator token="&gt;="/>
		<operator token="&lt;="/>
	</type>
	<type name="time" default="=">
		<!-- time or duration value in fixed format "hh:mm:ss" -->
		<operator token="="/>
		<operator token="&gt;"/>
		<operator token="&lt;"/>
		<operator token="&gt;="/>
		<operator token="&lt;="/>
	</type>
	<type name="timestamp" default="=">
		<!-- date and time value in ISO-8601 format "yyyy-MM-dd hh:mm:ss" -->
		<operator token="="/>
		<operator token="&gt;"/>
		<operator token="&lt;"/>
		<operator token="&gt;="/>
		<operator token="&lt;="/>
	</type>
	<type name="boolean" default="=">
		<!-- values "true" or "false" -->
		<operator token="="/>
	</type>
	<type name="decimal" default="=">
		<!-- decimal value with "." as separator -->
		<operator token="="/>
		<operator token="&gt;"/>
		<operator token="&lt;"/>
		<operator token="&gt;="/>
		<operator token="&lt;="/>
	</type>
	<type name="integer" default="=">
		<!-- integer value -->
		<operator token="="/>
		<operator token="&gt;"/>
		<operator token="&lt;"/>
		<operator token="&gt;="/>
		<operator token="&lt;="/>
	</type>
</fieldtypes>
