=== ThULB/jportal/mycore/schema/MCRClassification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns:xlink="http://www.w3.org/1999/xlink" 
  elementFormDefault="qualified">

<xsd:import schemaLocation="xml-2001.xsd" namespace="http://www.w3.org/XML/1998/namespace"/>
<xsd:import schemaLocation="xlinks-2001.xsd" namespace="http://www.w3.org/1999/xlink"/>
 
<xsd:element type="MCRClass" name="mycoreclass"/>

<xsd:complexType name="MCRClass">
 <xsd:sequence>
  <xsd:element maxOccurs="unbounded" minOccurs="1" type="MCRClassLabel"
     name="label"/>
  <xsd:element maxOccurs="1" minOccurs="1" type="MCRClassCatgories" 
     name="categories"/>
 </xsd:sequence>
 <xsd:attribute use="required" type="xsd:string" name="ID"/>
</xsd:complexType>

<xsd:complexType name="MCRClassLabel">
 <xsd:simpleContent>
  <xsd:extension base="xsd:string">
   <xsd:attribute ref="xml:lang"/>
   <xsd:attribute use="required" type="xsd:string" name="text"/>
   <xsd:attribute type="xsd:string" name="description"/>
  </xsd:extension>
 </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="MCRClassURL">
<xsd:attribute use="optional" ref="xlink:type"/>
<xsd:attribute ref="xlink:href"/>
<xsd:attribute use="optional" ref="xlink:title"/>
<xsd:attribute use="optional" ref="xlink:label"/>
</xsd:complexType>

<xsd:complexType name="MCRClassCatgories">
 <xsd:sequence>
  <xsd:element maxOccurs="unbounded" minOccurs="1" type="MCRClassCategory"
     name="category"/>
 </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="MCRClassCategory">
 <xsd:sequence>
  <xsd:element maxOccurs="unbounded" minOccurs="1" type="MCRClassLabel"
     name="label"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="MCRClassURL"
     name="url"/>
  <xsd:element maxOccurs="unbounded" minOccurs="0" type="MCRClassCategory"
     name="category"/>
 </xsd:sequence>
 <xsd:attribute use="required" type="xsd:string" name="ID"/>
 <xsd:attribute use="optional" type="xsd:integer" name="counter"/>
</xsd:complexType>

</xsd:schema>

=== ThULB/jportal/jportal_mcr_module/src/main/resources/classifications/51_artGattungRez_ISIS.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="jportal_class_00000051">
    <label xml:lang="de" text="Gattung des rez. Werkes"/>
    <label xml:lang="en" text="Type of reviewed work"/>
    <label xml:lang="pl" text="Gatunek dzieła recenzowanego"/>
    <categories>
        <category ID="00001000">
            <label xml:lang="de" text="Anatomie"/>
            <label xml:lang="en" text="anatomy"/>
            <label xml:lang="pl" text="anatomia"/>
        </category>
        <category ID="00002000">
            <label xml:lang="de" text="Anthropologie"/>
            <label xml:lang="en" text="anthropology"/>
            <label xml:lang="pl" text="antropologia"/>
        </category>
        <category ID="00003000">
            <label xml:lang="de" text="Astronomie"/>
            <label xml:lang="en" text="astronomy"/>
            <label xml:lang="pl" text="astronomia"/>
        </category>
        <category ID="00004000">
            <label xml:lang="de" text="Bauwesen"/>
            <label xml:lang="en" text="construction industry"/>
            <label xml:lang="pl" text="budownictwo"/>
        </category>
        <category ID="00005000">
            <label xml:lang="de" text="Botanik"/>
            <label xml:lang="en" text="botany"/>
            <label xml:lang="pl" text="botanika"/>
        </category>
        <category ID="00006000">
            <label xml:lang="de" text="Chemie"/>
            <label xml:lang="en" text="chemistry"/>
            <label xml:lang="pl" text="chemia"/>
        </category>
        <category ID="00007000">
            <label xml:lang="de" text="Diverses"/>
            <label xml:lang="en" text="miscellaneous material"/>
            <label xml:lang="pl" text="teksty rozmaite"/>
        </category>
        <category ID="00008000">
            <label xml:lang="de" text="Erziehungswissenschaft"/>
            <label xml:lang="en" text="pedagogy"/>
            <label xml:lang="pl" text="pedagogika"/>
        </category>
        <category ID="00009000">
            <label xml:lang="de" text="Forstwesen"/>
            <label xml:lang="en" text="forestry"/>
            <label xml:lang="pl" text="leśnictwo"/>
        </category>
        <category ID="00010000">
            <label xml:lang="de" text="Geographie"/>
            <label xml:lang="en" text="geography"/>
            <label xml:lang="pl" text="geografia"/>
        </category>
        <category ID="00011000">
            <label xml:lang="de" text="Geologie"/>
            <label xml:lang="en" text="geology"/>
            <label xml:lang="pl" text="geologia"/>
        </category>
        <category ID="00012000">
            <label xml:lang="de" text="Gerichtsmedizin"/>
            <label xml:lang="en" text="forensic medicine"/>
            <label xml:lang="pl" text="medycyna sądowa"/>
        </category>
        <category ID="00013000">
            <label xml:lang="de" text="Geschichte"/>
            <label xml:lang="en" text="history"/>
            <label xml:lang="pl" text="historia"/>
        </category>
        <category ID="00014000">
            <label xml:lang="de" text="Kunst"/>
            <label xml:lang="en" text="art"/>
            <label xml:lang="pl" text="sztuka"/>
        </category>
        <category ID="00015000">
            <label xml:lang="de" text="Landeskunde"/>
            <label xml:lang="en" text="regional studies"/>
            <label xml:lang="pl" text="krajoznawstwo"/>
        </category>
        <category ID="00016000">
            <label xml:lang="de" text="Literatur"/>
            <label xml:lang="en" text="literature"/>
            <label xml:lang="pl" text="literatura"/>
        </category>
        <category ID="00017000">
            <label xml:lang="de" text="Mathematik"/>
            <label xml:lang="en" text="mathematics"/>
            <label xml:lang="pl" text="matematyka"/>
        </category>
        <category ID="00018000">
            <label xml:lang="de" text="Medizin"/>
            <label xml:lang="en" text="medicine"/>
            <label xml:lang="pl" text="medycyna"/>
        </category>
        <category ID="00019000">
            <label xml:lang="de" text="Meteorologie"/>
            <label xml:lang="en" text="meteorology"/>
            <label xml:lang="pl" text="meteorologia"/>
        </category>
        <category ID="00020000">
            <label xml:lang="de" text="Mineralogie"/>
            <label xml:lang="en" text="mineralogy"/>
            <label xml:lang="pl" text="mineralogia"/>
        </category>
        <category ID="00021000">
            <label xml:lang="de" text="Naturgeschichte"/>
            <label xml:lang="en" text="natural history"/>
            <label xml:lang="pl" text="historia naturalna"/>
        </category>
        <category ID="00022000">
            <label xml:lang="de" text="Naturkunde"/>
            <label xml:lang="en" text="natural science"/> ????????????
            <label xml:lang="pl" text="przyrodoznawstwo"/>
        </category>
        <category ID="00023000">
            <label xml:lang="de" text="Naturphilosophie"/>
            <label xml:lang="en" text="natural philosophy"/>
            <label xml:lang="pl" text="filozofia przyrody"/>
        </category>
        <category ID="00024000">
            <label xml:lang="de" text="Ökonomie"/>
            <label xml:lang="en" text="economy"/>
            <label xml:lang="pl" text="ekonomia"/>
        </category>
        <category ID="00025000">
            <label xml:lang="de" text="Pharmazie"/>
            <label xml:lang="en" text="pharmacy"/>
            <label xml:lang="pl" text="farmacja"/>
        </category>
        <category ID="00026000">
            <label xml:lang="de" text="Philosophie"/>
            <label xml:lang="en" text="philosophy"/>
            <label xml:lang="pl" text="filozofia"/>
        </category>
        <category ID="00027000">
            <label xml:lang="de" text="Physik"/>
            <label xml:lang="en" text="physics"/>
            <label xml:lang="pl" text="fizyka"/>
        </category>
        <category ID="00028000">
            <label xml:lang="de" text="Physiologie"/>
            <label xml:lang="en" text="physiology"/>
            <label xml:lang="pl" text="fizjologia"/>
        </category>
        <category ID="00029000">
            <label xml:lang="de" text="Rechtswissenschaft"/>
            <label xml:lang="en" text="jurisprudence"/>
            <label xml:lang="pl" text="prawoznawstwo"/>
        </category>
        <category ID="00030000">
            <label xml:lang="de" text="Reisen"/>
            <label xml:lang="en" text="journeys"/>
            <label xml:lang="pl" text="podróże"/>
        </category>
        <category ID="00031000">
            <label xml:lang="de" text="Religion"/>
            <label xml:lang="en" text="religion"/>
            <label xml:lang="pl" text="religia"/>
        </category>
        <category ID="00032000">
            <label xml:lang="de" text="Zoologie"/>
            <label xml:lang="en" text="zoology"/>
            <label xml:lang="pl" text="zoologia"/>
        </category>
    </categories>
</mycoreclass>

=== ThULB/jportal/jportal_fsu_module/src/main/resources/content/classification/44_jportal_class_00000044_PHIL4_types.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd"
	ID="jportal_class_00000044">
	<label xml:lang="de" text="PHIL 4 - Classification for PHIL."/>
	<categories>
		<category ID="00001000">
			<label xml:lang="de" text="Abbildungen"/>
		</category>
		<category ID="00002000">
			<label xml:lang="de" text="Anzeigen"/>
		</category>
		<category ID="00003000">
			<label xml:lang="de" text="Artikel"/>
		</category>
		<category ID="00004000">
			<label xml:lang="de" text="Bibliographie"/>
		</category>
		<category ID="00005000">
			<label xml:lang="de" text="Katalog"/>
		</category>
		<category ID="00006000">
			<label xml:lang="de" text="Rezension"/>
		</category>
		<category ID="00007000">
			<label xml:lang="de" text="Tabellen"/>
		</category>
		<category ID="00008000">
			<label xml:lang="de" text="Verzeichnis"/>
		</category>
	</categories>
</mycoreclass>

=== ThULB/jportal/myjportal/modules/module-jportal/content/classification/65_rubricsZevru.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="jportal_class_00000065">
    <label xml:lang="de" text="Rubrik" description="Rubrik" />
    <label xml:lang="en" text="Rubric" description="Rubric" />
    <categories>
        <category ID="meditation">
            <label xml:lang="de" text="Andachten" />
        </category>
        <category ID="essay">
            <label xml:lang="de" text="AufsÃ¤tze" />
        </category>
        <category ID="report">
            <label xml:lang="de" text="Berichte" />
        </category>
        <category ID="literature">
            <label xml:lang="de" text="Literatur" />
        </category>
    </categories>
</mycoreclass>

=== ThULB/jportal/jpApp/myjportal/modules/jportal/content/classification/49_artLang_ISIS.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="jportal_class_00000049">
    <label xml:lang="de" text="Textsprache"/>
    <categories>
        <category ID="00001000">
            <label xml:lang="de" text="deutsch"/>
        </category>
        <category ID="00002000">
            <label xml:lang="de" text="deutsch / französisch"/>
        </category>
        <category ID="00003000">
            <label xml:lang="de" text="deutsch / griechisch"/>
        </category>
        <category ID="00004000">
            <label xml:lang="de" text="deutsch / latein"/>
        </category>
        <category ID="00005000">
            <label xml:lang="de" text="deutsch / russisch"/>
        </category>
        <category ID="00006000">
            <label xml:lang="de" text="deutsch / ungarisch"/>
        </category>
        <category ID="00007000">
            <label xml:lang="de" text="englisch"/>
        </category>
        <category ID="00008000">
            <label xml:lang="de" text="englisch / latein"/>
        </category>
        <category ID="00009000">
            <label xml:lang="de" text="französisch"/>
        </category>
        <category ID="00010000">
            <label xml:lang="de" text="französisch / latein"/>
        </category>
        <category ID="00011000">
            <label xml:lang="de" text="italienisch"/>
        </category>
        <category ID="00012000">
            <label xml:lang="de" text="latein"/>
        </category>
        <category ID="00013000">
            <label xml:lang="de" text="niederländisch"/>
        </category>
        <category ID="00014000">
            <label xml:lang="de" text="schwedisch"/>
        </category>
    </categories>
</mycoreclass>

=== ThULB/jportal/myjportal/content/classification/docportal_jstclass_contchild_type.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" 
      ID="DocPortal_class_10000010" >
      <label xml:lang="de" text="JST Art des Child Containers" description="erklrung zur atr des child-containers" />
      <categories>
            <category ID="TYPE0001">
                  <label xml:lang="de" text="Band" />
            </category>
            <category ID="TYPE0002">
                  <label xml:lang="de" text="Ausgabe" />
            </category>
            <category ID="TYPE0003">
                  <label xml:lang="de" text="Heft" />
            </category>
            <category ID="TYPE0004">
                  <label xml:lang="de" text="Nummer" />
            </category>            
      </categories>
</mycoreclass>

=== ThULB/jportal/src/main/resources/classifications/80_tradition.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd"
	ID="jportal_class_00000080" >
	<label xml:lang="de" text="Ãœberlieferung"/>
	<label xml:lang="en" text="Tradition"/>
	<categories>
		<category ID="altenburg">
			<label xml:lang="de" text="In der Altenburger Sammlung"/>
			<label xml:lang="en" text="In the Altenburg Collection"/>
		</category>
		<category ID="otherLocation">
			<label xml:lang="de" text="Weitere Standorte"/>
			<label xml:lang="en" text="Other location"/>
		</category>
	</categories>
</mycoreclass>

=== ThULB/jportal/jportal_fsu_module/src/main/resources/classifications/68_ezb.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="jportal_class_00000068">
    <label xml:lang="de" text="Kategorien EZB" description="Kategorien EZB" />
    <categories>
        <category ID="AVSL">
            <label xml:lang="de"
                text="Allgemeine und vergleichende Sprach- und Literaturwissenschaft.Indogermanistik.Aussereuropäische Sprachen und Literaturen." />
        </category>
        <category ID="ALL">
            <label xml:lang="de" text="Allgemeines, Fachübergreifendes" />
        </category>
        <category ID="ANGL">
            <label xml:lang="de" text="Anglistik. Amerikanistik" />
        </category>
        <category ID="ARCH">
            <label xml:lang="de" text="Archäologie" />
        </category>
        <category ID="BAU">
            <label xml:lang="de" text="Architektur, Bauingenieur- und Vermessungswesen" />
        </category>
        <category ID="BILD">
            <label xml:lang="de" text="Bildungsgeschichte" />
        </category>
        <category ID="BIO">
            <label xml:lang="de" text="Biologie" />
        </category>
        <category ID="CHEM">
            <label xml:lang="de" text="Chemie und Pharmazie" />
        </category>
        <category ID="ELECTRO">
            <label xml:lang="de" text="Elektrotechnik,Mess- und Regelungstechnik" />
        </category>
        <category ID="ENERGY">
            <label xml:lang="de" text="Energie, Umweltschutz, Kerntechnik" />
        </category>
        <category ID="ETHNO">
            <label xml:lang="de" text="Ethnologie (Volks- und Völkerkunde)" />
        </category>
        <category ID="GEO">
            <label xml:lang="de" text="Geographie" />
        </category>
        <category ID="GEOWISS">
            <label xml:lang="de" text="Geowissenschaften" />
        </category>
        <category ID="GERMA">
            <label xml:lang="de" text="Germanistik. Niederländische Philologie. Skandinavistik" />
        </category>
        <category ID="GESCH">
            <label xml:lang="de" text="Geschichte" />
        </category>
        <category ID="INFO">
            <label xml:lang="de" text="Informatik" />
        </category>
        <category ID="BUCHWESEN">
            <label xml:lang="de" text="Informations-, Buch- und Bibliothekswesen, Schrift- und Handschriftenkunde" />
        </category>
        <category ID="PHILO">
            <label xml:lang="de" text="Klassische Philologie. Byzantinistik. Mittellateinische und neugriechische Philologie. Neulatein" />
        </category>
        <category ID="KUNST">
            <label xml:lang="de" text="Kunstgeschichte" />
        </category>
        <category ID="LANDWIRT">
            <label xml:lang="de" text="Land- und Forstwirtschaft. Gartenbau. Fischereiwirtschaft. Hauswirtschaft. Ernährung" />
        </category>
        <category ID="MASCHINEN">
            <label xml:lang="de" text="Maschinenwesen, Werkstoffwissenschaften, Fertigungstechnik, Bergbau u. Hüttenwesen, Verkehrstechnik, Feinwerktechnik" />
        </category>
        <category ID="MATHE">
            <label xml:lang="de" text="Mathematik" />
        </category>
        <category ID="MEDIEN">
            <label xml:lang="de" text="Medien- und Kommunikationswissenschaften, Publizistik" />
        </category>
        <category ID="MED">
            <label xml:lang="de" text="Medizin" />
        </category>
        <category ID="MUSIK">
            <label xml:lang="de" text="Musikwissenschaft" />
        </category>
        <category ID="NATUR">
            <label xml:lang="de" text="Naturwissenschaft allgemein" />
        </category>
        <category ID="PÄD">
            <label xml:lang="de" text="Pädagogik" />
        </category>
        <category ID="PHI">
            <label xml:lang="de" text="Philosophie" />
        </category>
        <category ID="PHY">
            <label xml:lang="de" text="Physik" />
        </category>
        <category ID="POLIT">
            <label xml:lang="de" text="Politologie" />
        </category>
        <category ID="PSYCH">
            <label xml:lang="de" text="Psychologie" />
        </category>
        <category ID="RECHT">
            <label xml:lang="de" text="Rechtswissenschaft" />
        </category>
        <category ID="ROMAN">
            <label xml:lang="de" text="Romanistik" />
        </category>
        <category ID="SLAV">
            <label xml:lang="de" text="Slavistik" />
        </category>
        <category ID="SOZIO">
            <label xml:lang="de" text="Soziologie" />
        </category>
        <category ID="SPORT">
            <label xml:lang="de" text="Sport" />
        </category>
        <category ID="TECH">
            <label xml:lang="de" text="Technik allgemein" />
        </category>
        <category ID="THEO">
            <label xml:lang="de" text="Theologie und Religionswissenschaft" />
        </category>
        <category ID="VERF">
            <label xml:lang="de" text="Verfahrenstechnik, Biotechnologie, Lebensmitteltechnologie" />
        </category>
        <category ID="WIWI">
            <label xml:lang="de" text="Wirtschaftswissenschaften" />
        </category>
        <category ID="WIKUNDE">
            <label xml:lang="de" text="Wissenschaftskunde, Forschung, Hochschul-. Museumswesen" />
        </category>
    </categories>
</mycoreclass>

=== ThULB/jportal/myjportal/content/classification/jstApp_rubrics.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" 
      ID="DocPortal_class_20000010" >
      <label xml:lang="de" text="Rubriken JALZ" description="Rubriken JALZ" />
      <categories>
            <category ID="00002000">
                  <label xml:lang="de" text="Normalblatt" />
                  <category ID="00002000.00001000">
                        <label xml:lang="de" text="Alte Literatur" />
                  </category>
                  <category ID="00002000.00002000">
                        <label xml:lang="de" text="Altenthmer" />
                  </category>
                  <category ID="00002000.00003000">
                        <label xml:lang="de" text="Architektonik" />
                  </category>
                  <category ID="00002000.00005000">
                        <label xml:lang="de" text="Auslndische Sprachkunde" />
                  </category>
                  <category ID="00002000.00006000">
                        <label xml:lang="de" text="Biblische Literatur" />
                  </category>
                  <category ID="00002000.00007000">
                        <label xml:lang="de" text="Botanik" />
                  </category>
                  <category ID="00002000.00008000">
                        <label xml:lang="de" text="Chemie" />
                  </category>
                  <category ID="00002000.00009000">
                        <label xml:lang="de" text="Deutsche Sprachkunde" />
                  </category>
                  <category ID="00002000.00010000">
                        <label xml:lang="de" text="Deutsche Sprachkunst" />
                  </category>
                  <category ID="00002000.00011000">
                        <label xml:lang="de" text="Diplomatik" />
                  </category>
                  <category ID="00002000.00012000">
                        <label xml:lang="de" text="Erbaungsschriften" />
                  </category>
                  <category ID="00002000.00013000">
                        <label xml:lang="de" text="Erdbeschreibung" />
                  </category>
                  <category ID="00002000.00014000">
                        <label xml:lang="de" text="Erziehungskunde" />
                  </category>
                  <category ID="00002000.00015000">
                        <label xml:lang="de" text="Freimaurerschriften" />
                  </category>
                  <category ID="00002000.00016000">
                        <label xml:lang="de" text="Geschichte" />
                  </category>
                  <category ID="00002000.00017000">
                        <label xml:lang="de" text="Griechische Literatur" />
                  </category>
                  <category ID="00002000.00018000">
                        <label xml:lang="de" text="Handlungswissenschaften" />
                  </category>
                  <category ID="00002000.00019000">
                        <label xml:lang="de" text="Jugendschriften" />
                  </category>
                  <category ID="00002000.00020000">
                        <label xml:lang="de" text="Jurisprudenz" />
                  </category>
                  <category ID="00002000.00021000">
                        <label xml:lang="de" text="Kinderschriften" />
                  </category>
                  <category ID="00002000.00022000">
                        <label xml:lang="de" text="Kirchengeschichte" />
                  </category>
                  <category ID="00002000.00024000">
                        <label xml:lang="de" text="Kirchengeschichten" />
                  </category>
                  <category ID="00002000.00025000">
                        <label xml:lang="de" text="Kriegswissenschaften" />
                  </category>
                  <category ID="00002000.00026000">
                        <label xml:lang="de" text="Lateinische Sprachkunde" />
                  </category>
                  <category ID="00002000.00027000">
                        <label xml:lang="de" text="Literaturgeschichte" />
                  </category>
                  <category ID="00002000.00028000">
                        <label xml:lang="de" text="Mathematik" />
                  </category>
                  <category ID="00002000.00029000">
                        <label xml:lang="de" text="Medicin" />
                  </category>
                  <category ID="00002000.00030000">
                        <label xml:lang="de" text="Naturgeschichte" />
                  </category>
                  <category ID="00002000.00031000">
                        <label xml:lang="de" text="Naturlehre" />
                  </category>
                  <category ID="00002000.00032000">
                        <label xml:lang="de" text="Neuere Sprachkunde" />
                  </category>
                  <category ID="00002000.00033000">
                        <label xml:lang="de" text="Numismatik" />
                  </category>
                  <category ID="00002000.00034000">
                        <label xml:lang="de" text="Oekonomie" />
                  </category>
                  <category ID="00002000.00036000">
                        <label xml:lang="de" text="Orientalische Literatur" />
                  </category>
                  <category ID="00002000.00037000">
                        <label xml:lang="de" text="Pdagogik" />
                  </category>
                  <category ID="00002000.00038000">
                        <label xml:lang="de" text="Philologik" />
                  </category>
                  <category ID="00002000.00039000">
                        <label xml:lang="de" text="Philosophie" />
                  </category>
                  <category ID="00002000.00040000">
                        <label xml:lang="de" text="Physik" />
                  </category>
                  <category ID="00002000.00041000">
                        <label xml:lang="de" text="Rmische Literatur" />
                  </category>
                  <category ID="00002000.00042000">
                        <label xml:lang="de" text="Schne Anzeigen" />
                  </category>
                  <category ID="00002000.00043000">
                        <label xml:lang="de" text="Schne Knste" />
                  </category>
                  <category ID="00002000.00044000">
                        <label xml:lang="de" text="Sprachkunde" />
                  </category>
                  <category ID="00002000.00045000">
                        <label xml:lang="de" text="Staatswissenschaften" />
                  </category>
                  <category ID="00002000.00046000">
                        <label xml:lang="de" text="Statistik" />
                  </category>
                  <category ID="00002000.00047000">
                        <label xml:lang="de" text="Technologie" />
                  </category>
                  <category ID="00002000.00048000">
                        <label xml:lang="de" text="Theologie" />
                  </category>
                  <category ID="00002000.00049000">
                        <label xml:lang="de" text="Vermischte Schriften" />
                  </category>
            </category>
            <category ID="00003000">
                  <label xml:lang="de" text="Intelligenzblatt" />
                  <category ID="00003000.00001000">
                        <label xml:lang="de" text="wird noch erstellt" />
                  </category>
            </category>
      </categories>
</mycoreclass>
