=== ThULB/jportal/mycore/schema/MCRClassification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns:xlink="http://www.w3.org/1999/xlink" 
  elementFormDefault="qualified">

<xsd:import schemaLocation="xml-2001.xsd" namespace="http://www.w3.org/XML/1998/namespace"/>
<xsd:import schemaLocation="xlinks-2001.xsd" namespace="http://www.w3.org/1999/xlink"/>
 
<xsd:element type="MCRClass" name="mycoreclass"/>

<xsd:complexType name="MCRClass">
 <xsd:sequence>
  <xsd:element maxOccurs="unbounded" minOccurs="1" type="MCRClassLabel"
     name="label"/>
  <xsd:element maxOccurs="1" minOccurs="1" type="MCRClassCatgories" 
     name="categories"/>
 </xsd:sequence>
 <xsd:attribute use="required" type="xsd:string" name="ID"/>
</xsd:complexType>

<xsd:complexType name="MCRClassLabel">
 <xsd:simpleContent>
  <xsd:extension base="xsd:string">
   <xsd:attribute ref="xml:lang"/>
   <xsd:attribute use="required" type="xsd:string" name="text"/>
   <xsd:attribute type="xsd:string" name="description"/>
  </xsd:extension>
 </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="MCRClassURL">
<xsd:attribute use="optional" ref="xlink:type"/>
<xsd:attribute ref="xlink:href"/>
<xsd:attribute use="optional" ref="xlink:title"/>
<xsd:attribute use="optional" ref="xlink:label"/>
</xsd:complexType>

<xsd:complexType name="MCRClassCatgories">
 <xsd:sequence>
  <xsd:element maxOccurs="unbounded" minOccurs="1" type="MCRClassCategory"
     name="category"/>
 </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="MCRClassCategory">
 <xsd:sequence>
  <xsd:element maxOccurs="unbounded" minOccurs="1" type="MCRClassLabel"
     name="label"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="MCRClassURL"
     name="url"/>
  <xsd:element maxOccurs="unbounded" minOccurs="0" type="MCRClassCategory"
     name="category"/>
 </xsd:sequence>
 <xsd:attribute use="required" type="xsd:string" name="ID"/>
 <xsd:attribute use="optional" type="xsd:integer" name="counter"/>
</xsd:complexType>

</xsd:schema>

=== ThULB/jportal/myjportal/modules/jportal/content/classification/46_artpubTypes_ISIS.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="jportal_class_00000046">
    <label xml:lang="de" text="Textsorte"/>
    <categories>
        <category ID="00001000">
            <label xml:lang="de" text="Abhandlungen aus andern, vorzüglich fremden Zeitschriften"/>
        </category>
        <category ID="00002000">
            <label xml:lang="de" text="Arbeiten gelehrter Männer und Gesellschaften"/>
        </category>
        <category ID="00003000">
            <label xml:lang="de" text="Auszüge aus Büchern"/>
        </category>
        <category ID="00004000">
            <label xml:lang="de" text="Beförderungen der wissenschaften durch Gönner, Fürsten, Reiche"/>
        </category>
        <category ID="00005000">
            <label xml:lang="de" text="Bemerkungen"/>
        </category>
        <category ID="00006000">
            <label xml:lang="de" text="Beurtheilungen"/>
        </category>
        <category ID="00007000">
            <label xml:lang="de" text="Bücheranzeigen"/>
        </category>
        <category ID="00008000">
            <label xml:lang="de" text="Entdeckungen und Reisen"/>
        </category>
        <category ID="00009000">
            <label xml:lang="de" text="Gelehrte Anfragen und Antworten, Berichtigungen"/>
        </category>
        <category ID="00010000">
            <label xml:lang="de" text="Inhalte von Dissertationen"/>
        </category>
        <category ID="00011000">
            <label xml:lang="de" text="Innhalt von Zeitschriften und Büchern"/>
        </category>
        <category ID="00012000">
            <label xml:lang="de" text="Korrespondenzen"/>
        </category>
        <category ID="00013000">
            <label xml:lang="de" text="Kritk und Antikritik"/>
        </category>
        <category ID="00014000">
            <label xml:lang="de" text="Leben und Weben und Sterben öffentlicher Menschen"/>
        </category>
        <category ID="00015000">
            <label xml:lang="de" text="Literarische Berichte"/>
        </category>
        <category ID="00016000">
            <label xml:lang="de" text="Literarisches Verzeichnis"/>
        </category>
        <category ID="00017000">
            <label xml:lang="de" text="Preisaufgaben"/>
        </category>
        <category ID="00018000">
            <label xml:lang="de" text="Uebersichten der Litteratur, der fremden wie der einheimischen"/>
        </category>
        <category ID="00019000">
            <label xml:lang="de" text="Ursprüngliche Abhandlungen"/>
        </category>
        <category ID="00020000">
            <label xml:lang="de" text="Vorleskataloge"/>
        </category>
        <category ID="00021000">
            <label xml:lang="de" text="Vortragsabdrucke"/>
        </category>
        <category ID="00022000">
            <label xml:lang="de" text="Vortragsinhalte"/>
        </category>
        <category ID="00023000">
            <label xml:lang="de" text="Zusätze und Berichtigungen"/>
        </category>
        <category ID="00024000">
            <label xml:lang="de" text="Zustand wiss. Anstalten, Bibliotheken, Sammlungen, Gärten und Tierhäuser"/>
        </category>
    </categories>
</mycoreclass>

=== ThULB/jportal/jportal_mcr_module/src/main/resources/classifications/210_jportal_journalType.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="jportal_class_00000210">
  <label xml:lang="de" text="Zeitschriftentyp" />
  <label xml:lang="en" text="Type of journal" />
  <categories>
    <category ID="legalDeposit">
      <label xml:lang="de" text="Pflichtexemplar" />
      <label xml:lang="en" text="Legal deposit" />
    </category>
    <category ID="onlineJournal">
      <label xml:lang="de" text="Online-Zeitschrift" />
      <label xml:lang="en" text="Online journal" />
    </category>
  </categories>
</mycoreclass>

=== ThULB/jportal/jportal_fsu_module/src/main/resources/classifications/48_artCountry_ISIS.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="jportal_class_00000048">
    <label xml:lang="de" text="Land"/>
    <categories>
        <category ID="00001000">
            <label xml:lang="de" text="Dänemark"/>
        </category>
        <category ID="00002000">
            <label xml:lang="de" text="Deutschland"/>
        </category>
        <category ID="00003000">
            <label xml:lang="de" text="England"/>
        </category>
        <category ID="00004000">
            <label xml:lang="de" text="Frankreich"/>
        </category>
        <category ID="00005000">
            <label xml:lang="de" text="Japan"/>
        </category>
        <category ID="00006000">
            <label xml:lang="de" text="Kolumbien"/>
        </category>
        <category ID="00007000">
            <label xml:lang="de" text="Niederlande"/>
        </category>
        <category ID="00008000">
            <label xml:lang="de" text="Östereich/Ungarn"/>
        </category>
        <category ID="00009000">
            <label xml:lang="de" text="Russland"/>
        </category>
        <category ID="00010000">
            <label xml:lang="de" text="Schottland"/>
        </category>
        <category ID="00011000">
            <label xml:lang="de" text="Schweden"/>
        </category>
        <category ID="00012000">
            <label xml:lang="de" text="Schweiz"/>
        </category>
        <category ID="00013000">
            <label xml:lang="de" text="Teneriffa"/>
        </category>
    </categories>
</mycoreclass>

=== ThULB/jportal/jportal_mcr_module/src/main/resources/classifications/65_rubricsZevru.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="jportal_class_00000065">
    <label xml:lang="de" text="Rubrik" description="Rubrik" />
    <label xml:lang="en" text="Rubric" description="Rubric" />
    <label xml:lang="pl" text="Rubryka" description="Rubryka" />
    <categories>
        <category ID="meditation">
            <label xml:lang="de" text="Andachten" />
            <label xml:lang="en" text="devotions" />
            <label xml:lang="pl" text="nabożeństwa" />
        </category>
        <category ID="essay">
            <label xml:lang="de" text="Aufsätze" />
            <label xml:lang="en" text="essays" />
            <label xml:lang="pl" text="esej" />
        </category>
        <category ID="report">
            <label xml:lang="de" text="Berichte" />
            <label xml:lang="en" text="reports" />
            <label xml:lang="pl" text="sprawozdania" />
        </category>
        <category ID="literature">
            <label xml:lang="de" text="Literatur" />
            <label xml:lang="en" text="literature" />
            <label xml:lang="pl" text="literatura" />
        </category>
    </categories>
</mycoreclass>

=== ThULB/jportal/application/modules/module-jportal/content/classification/typesOfDates_Journals.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd"
	ID="jportal_class_00000009">
	<label xml:lang="de" text="Datums-Typen in Journalen" description="Datums-Typen in Journalen"/>
	<categories>
		<category ID="published">
			<label xml:lang="de" text="Erschienen"/>
		</category>
		<category ID="published_from">
			<label xml:lang="de" text="Erschienen von"/>
		</category>
		<category ID="published_until">
			<label xml:lang="de" text="Erschienen bis"/>
		</category>
	</categories>
</mycoreclass>

=== ThULB/jportal/jportal_mcr_module/src/main/resources/classifications/48_artCountry_ISIS.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="jportal_class_00000048">
    <label xml:lang="de" text="Land"/>
    <label xml:lang="en" text="Country"/>
    <label xml:lang="pl" text="Kraj"/>
    <categories>
        <category ID="00001000">
            <label xml:lang="de" text="Dänemark"/>
            <label xml:lang="en" text="Denmark"/>
            <label xml:lang="pl" text="Dania"/>
        </category>
        <category ID="00002000">
            <label xml:lang="de" text="Deutschland"/>
            <label xml:lang="en" text="Germany"/>
            <label xml:lang="pl" text="Niemcy"/>
        </category>
        <category ID="00003000">
            <label xml:lang="de" text="England"/>
            <label xml:lang="en" text="England"/>
            <label xml:lang="pl" text="Anglia"/>
        </category>
        <category ID="00004000">
            <label xml:lang="de" text="Frankreich"/>
            <label xml:lang="en" text="France"/>
            <label xml:lang="pl" text="Francja"/>
        </category>
        <category ID="00005000">
            <label xml:lang="de" text="Japan"/>
            <label xml:lang="en" text="Japan"/>
            <label xml:lang="pl" text="Japonia"/>
        </category>
        <category ID="00006000">
            <label xml:lang="de" text="Kolumbien"/>
            <label xml:lang="en" text="Colombia"/>
            <label xml:lang="pl" text="Kolumbia"/>
        </category>
        <category ID="00007000">
            <label xml:lang="de" text="Niederlande"/>
            <label xml:lang="en" text="Netherlands"/>
            <label xml:lang="pl" text="Holandia"/>
        </category>
        <category ID="00008000">
            <label xml:lang="de" text="Östereich-Ungarn"/>
            <label xml:lang="en" text="Austria-Hungary"/>
            <label xml:lang="pl" text="Austro-Węgry"/>
        </category>
        <category ID="00009000">
            <label xml:lang="de" text="Russland"/>
            <label xml:lang="en" text="Russia"/>
            <label xml:lang="pl" text="Rosja"/>
        </category>
        <category ID="00010000">
            <label xml:lang="de" text="Schottland"/>
            <label xml:lang="en" text="Scotland"/>
            <label xml:lang="pl" text="Szkocja"/>
        </category>
        <category ID="00011000">
            <label xml:lang="de" text="Schweden"/>
            <label xml:lang="en" text="Sweden"/>
            <label xml:lang="pl" text="Szwecja"/>
        </category>
        <category ID="00012000">
            <label xml:lang="de" text="Schweiz"/>
            <label xml:lang="en" text="Switzerland"/>
            <label xml:lang="pl" text="Szwajcaria"/>
        </category>
        <category ID="00013000">
            <label xml:lang="de" text="Teneriffa"/>
            <label xml:lang="en" text="Tenerife"/>
            <label xml:lang="pl" text="Teneryfa"/>
        </category>
    </categories>
</mycoreclass>

=== ThULB/jportal/jportal_mcr_module/src/main/resources/classifications/43_jportal_class_00000043_PHIL5_types.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd"
	ID="jportal_class_00000043">
	<label xml:lang="de" text="PHIL V - Classification for PHIL."/>
	<categories>
		<category ID="00001000">
			<label xml:lang="de" text="Abbildungen"/>
			<label xml:lang="en" text="Illustrations"/>
			<label xml:lang="pl" text="Ilustracje"/>
		</category>
		<category ID="00002000">
			<label xml:lang="de" text="Artikel"/>
			<label xml:lang="en" text="Article"/>
			<label xml:lang="pl" text="ArtykuÅ‚"/>
		</category>
		<category ID="00003000">
			<label xml:lang="de" text="Karten"/>
			<label xml:lang="en" text="Maps"/>
			<label xml:lang="pl" text="Mapy"/>
		</category>
		<category ID="00004000">
			<label xml:lang="de" text="Tabelle"/>
			<label xml:lang="en" text="Chart"/>
			<label xml:lang="pl" text="Tabela"/>
		</category>
		<category ID="00005000">
			<label xml:lang="de" text="Verzeichnis"/>
			<label xml:lang="en" text="Directory"/>
			<label xml:lang="pl" text="Spis"/>
		</category>
	</categories>
</mycoreclass>

=== ThULB/jportal/jportal_fsu_module/src/main/resources/content/classification/50_artGattung1826_ISIS.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="jportal_class_00000050">
    <label xml:lang="de" text="Gattung 1826"/>
    <categories>
        <category ID="00001000">
            <label xml:lang="de" text="I.a) Naturgeschichte"/>
        </category>
        <category ID="00002000">
            <label xml:lang="de" text="I.b) Zoologie"/>
        </category>
        <category ID="00003000">
            <label xml:lang="de" text="I.c) Anatomie"/>
        </category>
        <category ID="00004000">
            <label xml:lang="de" text="I.d) Physiologie"/>
        </category>
        <category ID="00005000">
            <label xml:lang="de" text="I.e) Medizin"/>
        </category>
        <category ID="00006000">
            <label xml:lang="de" text="I.f) Botantik"/>
        </category>
        <category ID="00007000">
            <label xml:lang="de" text="I.g) Mineralogie"/>
        </category>
        <category ID="00008000">
            <label xml:lang="de" text="I.h) Chemie"/>
        </category>
        <category ID="00009000">
            <label xml:lang="de" text="I.i) Physik"/>
        </category>
        <category ID="00010000">
            <label xml:lang="de" text="I.k) Mathematik"/>
        </category>
        <category ID="00011000">
            <label xml:lang="de" text="I.m) Reisen"/>
        </category>
        <category ID="00012000">
            <label xml:lang="de" text="II.n) Geographie"/>
        </category>
        <category ID="00013000">
            <label xml:lang="de" text="II.o) Geschichte"/>
        </category>
        <category ID="00014000">
            <label xml:lang="de" text="II.p) Aesthetik, Kunst und Sprachen"/>
        </category>
        <category ID="00015000">
            <label xml:lang="de" text="II.q) Philosophie"/>
        </category>
        <category ID="00016000">
            <label xml:lang="de" text="II.r) Litteratur"/>
        </category>
        <category ID="00017000">
            <label xml:lang="de" text="II.s) Gewerbe, Oeconomie und Technologie"/>
        </category>
    </categories>
</mycoreclass>
