=== ThULB/jportal/mycore/schema/MCRUser.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified">

<xsd:import schemaLocation="xml-2001.xsd"
  namespace="http://www.w3.org/XML/1998/namespace"/>

<xsd:element type="MCRUser" name="mycoreuser"/>

<xsd:complexType name="MCRUser">
 <xsd:sequence>
  <xsd:element maxOccurs="unbounded" minOccurs="1" type="User" name="user"/>
 </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="User">
 <xsd:all>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="user.creator"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="user.creation_date"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="user.last_modified"/>
  <xsd:element maxOccurs="1" minOccurs="1" type="xsd:string" name="user.password"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="user.description"/>
  <xsd:element maxOccurs="1" minOccurs="1" type="xsd:string" name="user.primary_group"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="UserContact" name="user.contact"/>
  <xsd:element maxOccurs="1" minOccurs="0" name="user.groups">
   <xsd:complexType>
    <xsd:sequence>
     <xsd:element maxOccurs="unbounded" minOccurs="1" name="groups.groupID">
      <xsd:complexType>
       <xsd:simpleContent>
        <xsd:extension base="xsd:string"/>
       </xsd:simpleContent>
      </xsd:complexType>
     </xsd:element>
    </xsd:sequence>
   </xsd:complexType>
  </xsd:element>
 </xsd:all>
 <xsd:attribute use="required" type="xsd:string" name="ID"/>
 <xsd:attribute use="required" type="xsd:string" name="numID"/>
 <xsd:attribute use="required" type="xsd:boolean" name="id_enabled"/>
 <xsd:attribute use="required" type="xsd:boolean" name="update_allowed"/>
</xsd:complexType>

<xsd:complexType name="UserContact">
 <xsd:sequence>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.salutation"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.firstname"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.lastname"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.street"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.city"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.postalcode"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.country"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.state"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.institution"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.faculty"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.department"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.institute"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.telephone"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.fax"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.email"/>
  <xsd:element maxOccurs="1" minOccurs="0" type="xsd:string" name="contact.cellphone"/>
 </xsd:sequence>
</xsd:complexType>

</xsd:schema>

=== ThULB/jportal/application/modules/docportal/config/user/user_author2A.xml
<?xml version="1.0" encoding="ISO_8859-1"?>
<mycoreuser xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:noNamespaceSchemaLocation="MCRUser.xsd">
  <user numID="15" ID="author2A" id_enabled="true" update_allowed="true">
    <user.password>author2A</user.password>
    <user.description>Bereichtigter Autor der Gruppe 2</user.description>
    <user.primary_group>authorgroup2</user.primary_group>
    <user.contact>
      <contact.salutation />
      <contact.firstname />
      <contact.lastname>Autor A der Gruppe 2</contact.lastname>
      <contact.street />
      <contact.city />
      <contact.postalcode />
      <contact.country />
      <contact.state />
      <contact.institution />
      <contact.faculty />
      <contact.department />
      <contact.institute />
      <contact.telephone />
      <contact.fax />
      <contact.email />
      <contact.cellphone />
    </user.contact>
  </user>
</mycoreuser>
