=== ThULB/jportal/jportal_laws/src/main/resources/Gesetzessammlung.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xlink="http://www.w3.org/1999/xlink"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

  <xs:element name="gesetzessammlung">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="register" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="register">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titel" type="xs:string" />
        <xs:element ref="jahresangabe" />
        <xs:element name="herzogtum" type="xs:string" />
        <xs:element ref="gesetze" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="jahresangabe">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="von" type="xs:integer" />
        <xs:element name="bis" type="xs:integer" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="gesetze">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="gesetz" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="gesetz">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nummer" type="xs:integer" minOccurs="0" />
        <xs:element ref="inhalt" />
        <xs:element ref="datum"/>
        <xs:element ref="seite"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="inhalt">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="ol" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="ol">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="li" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="type" type="orderType" default="numerical"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="li">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="ol" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="orderType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="alphabetical" />
      <xs:enumeration value="numerical" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="datum">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="erlass" type="xs:date" maxOccurs="unbounded" />
        <xs:element name="ausgabe" type="xs:date" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="seite">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="von" type="xs:integer" />
        <xs:element name="bis" type="xs:integer" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== ThULB/jportal/jportal_laws/src/main/resources/web/register/Sachsen-Altenburg/1823_Register.xml
<?xml version="1.0" encoding="UTF-8"?><gesetzessammlung xmlns="http://www.thulb.uni-jena.de/gesetzessammlung/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.thulb.uni-jena.de/gesetzessammlung/Gesetzessammlung.xsd"><register><titel>Repertorium der Gesetz-Sammlung für das Herzogthum Altenburg vom Jahre 1823.</titel><jahresangabe><von>1823</von></jahresangabe><herzogtum>Sachsen-Altenburg</herzogtum><gesetze><gesetz><nummer>1</nummer><inhalt>Verordnung der Landes-Regierung, wodurch die in Betreff der Pfuscherey in die Medicin und Chirurgie und des unbefugten Arzneyhandels vorhandenen gesetzlichen Verordnungen eingeschärft werden</inhalt><datum><erlass>1823-01-11</erlass><ausgabe>1823-01-21</ausgabe></datum><seite><von>1</von><bis>1</bis></seite></gesetz><gesetz><nummer>2</nummer><inhalt>Bekanntmachung der Landes-Regierung, daß zwischen dem Sachsen-Gotha-Altenburgischen und dem Königl. Preuß. Ministerium die vorläufige Uebereinkunft getroffen worden ist, daß sich in allen vorkommenden Fällen, welche die Uebernahme von Vagabunden und Ausgewiesenen betreffen, nach der deshalb mit dem Königl. Sächs. Gouvernement abgeschlossenen Convention gerichtet werden soll</inhalt><datum><erlass>1823-02-01</erlass><ausgabe>1823-02-11</ausgabe></datum><seite><von>2</von><bis>2</bis></seite></gesetz><gesetz><nummer>3</nummer><inhalt>Bekanntmachung der Landes-Regierung, daß zwischen dem Sachsen-Gotha-Altenburgischen und dem Kurhessischen Ministerium wegen wechselseitiger Uebernahme der Vagabunden und Ausgewiesenen dieselbe Convention abgeschlossen worden, welche mit dem Königl. Sächs. Gouvernement getroffen worden ist</inhalt><datum><erlass>1823-02-01</erlass><ausgabe>1823-02-11</ausgabe></datum><seite><von>3</von><bis>3</bis></seite></gesetz><gesetz><nummer>4</nummer><inhalt>Verordnung des Consistorii, die Ausleihung der Kirchen-Capitalien und die Führung der Kirchrechnungen betreffend</inhalt><datum><erlass>1823-02-04</erlass><ausgabe>1823-02-11</ausgabe></datum><seite><von>3</von><bis>4</bis></seite></gesetz><gesetz><nummer>5</nummer><inhalt>Verordnung der Landes-Regierung, die Einsendung der Polizey-Steuer betreffend</inhalt><datum><erlass>1823-02-05</erlass><ausgabe>1823-02-18</ausgabe></datum><seite><von>5</von><bis>5</bis></seite></gesetz><gesetz><nummer>6</nummer><inhalt>Verordnung der Landes-Regierung, das Colligiren für auswärtige Lotterien betreffend</inhalt><datum><erlass>1823-02-17</erlass><ausgabe>1823-02-25</ausgabe></datum><seite><von>5</von><bis>5</bis></seite></gesetz><gesetz><nummer>7</nummer><inhalt>Verordnung der Landes-Regierung, wodurch das Verbot, auf den Brand betteln zu gehen, erneuert und eingeschärft wird</inhalt><datum><erlass>1823-02-17</erlass><ausgabe>1823-02-25</ausgabe></datum><seite><von>6</von><bis>7</bis></seite></gesetz><gesetz><nummer>8</nummer><inhalt>Bekanntmachung der Landes-Regierung, daß die Deserteurs der Königl. Sächs. Truppen auf Requisition der Königl. Sächs. Behörden unter Zusicherung des Reciproci ausgeliefert werden sollen</inhalt><datum><erlass>1823-02-17</erlass><ausgabe>1823-02-25</ausgabe></datum><seite><von>8</von><bis>8</bis></seite></gesetz><gesetz><nummer>9</nummer><inhalt>Verordnung des Consistorii, daß diejenigen, welche wegen Fleischessünden Censur-Gebühren zu entrichten haben, bis zu deren Entrichtung von dem Genusse des heiligen Abendmahls nicht zurückzuhalten sind</inhalt><datum><erlass>1823-02-18</erlass><ausgabe>1823-03-18</ausgabe></datum><seite><von>9</von><bis>9</bis></seite></gesetz><gesetz><nummer>10</nummer><inhalt>Verordnung des Consistorii, daß die Kinder in dem letzten Schuljahre vor der Confirmation nicht vermiethet werden dürfen</inhalt><datum><erlass>1823-02-25</erlass><ausgabe>1823-03-11</ausgabe></datum><seite><von>10</von><bis>11</bis></seite></gesetz><gesetz><nummer>11</nummer><inhalt>Verordnung der Cammer, daß die Frohnpflichtigen die ihnen obliegenden Frohnfuhren zu der auf den Frohnzetteln angegebenen Zeit bestimmt zu leisten haben</inhalt><datum><erlass>1823-03-04</erlass><ausgabe>1823-03-11</ausgabe></datum><seite><von>12</von><bis>12</bis></seite></gesetz><gesetz><nummer>12</nummer><inhalt>Mandat, Erläuterungen und Zusätze zu der Proceß- und Advocaten-Ordnung enthaltend</inhalt><datum><erlass>1823-04-07</erlass><ausgabe>1823-06-24</ausgabe></datum><seite><von>13</von><bis>50</bis></seite></gesetz><gesetz><nummer>13</nummer><inhalt>Gesetz über den unbestimmten summarischen Proceß und das Rechnungs-Verfahren</inhalt><datum><erlass>1823-04-07</erlass><ausgabe>1823-07-29</ausgabe></datum><seite><von>51</von><bis>117</bis></seite></gesetz><gesetz><nummer>14</nummer><inhalt>Bekanntmachung der Landes-Regierung, daß zwischen dem Herzogl. Sachsen-Gotha-Altenburgischen und dem Herzogl. Sachsen-Meiningischen geheimen Ministerium wegen wechselseitiger Uebernahme der Vagabunden und Ausgewiesenen dieselbe Convention geschlossen worden, die mit dem Königl. Sächs. Gouvernement deshalb getroffen worden ist</inhalt><datum><erlass>1823-04-07</erlass><ausgabe>1823-04-22</ausgabe></datum><seite><von>118</von><bis>118</bis></seite></gesetz><gesetz><nummer>15</nummer><inhalt>Bekanntmachung des Consistorii, daß zu den Kosten, welche bey Anstellungen von Candidaten des Predigt-Amtes als Pfarrer, oder Pfarrsubstituten entstehen und aus dem Kirchen-Vermögen, oder aushülfsweise von den Kirchen-Gemeinden zu bezahlen sind, die Kosten der Reise zur Gastpredigt und Prüfung nicht zu rechnen sind</inhalt><datum><erlass>1823-04-08</erlass><ausgabe>1823-04-22</ausgabe></datum><seite><von>119</von><bis>119</bis></seite></gesetz><gesetz><nummer>16</nummer><inhalt>Verordnung der Landes-Regierung, den Verkauf von jungen Obst- und andern Bäumen betreffend</inhalt><datum><erlass>1823-05-03</erlass><ausgabe>1823-05-13</ausgabe></datum><seite><von>120</von><bis>120</bis></seite></gesetz><gesetz><nummer>17</nummer><inhalt>Verordnung der Landes-Regierung, daß die sämmtlichen Hebammen im Lande Geburts-Register nach den ihnen mitgetheilten Vorschriften zu führen und jährlich vor dem Schluß des Monats Januar an die in der Verordnung namhaft gemachten Personen einzusenden haben</inhalt><datum><erlass>1823-06-07</erlass><ausgabe>1823-06-17</ausgabe></datum><seite><von>121</von><bis>122</bis></seite></gesetz>
